#ifndef PREPARATIONSTATUS_H
#define PREPARATIONSTATUS_H


enum PreparationStatus {
    PREPARE_NOT_STARTED,
    PREPARE_IS_ALLOWED,
    PREPARE_ERROR_PAYMENT,
    PREPARE_ERROR_NO_CUP,
    PREPARE_ERROR_FULL_CUP,
    PREPARE_ERROR_NO_DRINK,
    PREPARE_ERROR_NO_CARD,
    PREPARE_IN_PROGRESS,
    PREPARE_ERROR_NO_INGREDIENT,
    PREPARE_ERROR_FLOW,
    PREPARE_ERROR_HEATER,
    PREPARE_DONE
};


#endif // PREPARATIONSTATUS_H
